### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by hrenard** [vknecht/droid-hal-idol3#1]
Hello,
First, thanks for your work !
I am trying to find if it's possible to get android support, i saw in the [changelog](https://wiki.merproject.org/wiki/Adaptations/libhybris/Install_SailfishOS_for_idol3) that there is kernel support for anbox as of alpha 5. Does this mean you managed to install it and if so how or just that the kernel is ready for a furtur version ?

**Comment by vknecht** [comment]
Hi :-)

Here's how to install sfos-anbox :

### As root (devel-su), on the phone via SSH :
### Add mal's Anbox for SFOS repository
ssu ar home_mal_anbox http://repo.merproject.org/obs/home:/mal:/anbox/sailfish_latest_armv7hl/
pkcon refresh
pkcon install anbox-sailfishos anbox-sailfishos-image-mixed-32-64-bit
rm -f /var/lib/anbox/overlay/system/lib64/libGLESv*
cp /vendor/lib/egl/libEGL_adreno.so /var/lib/anbox/overlay/vendor/lib/egl/
### Install a keyboard APK, eg https://f-droid.org/fr/packages/rkr.simplekeyboard.inputmethod/
mkdir -p /var/lib/anbox/data/app
cp *apk /var/lib/anbox/data/app
### Networking is broken at the moment...
### Comment anbox-bridge.sh lines (ExecStartPre and ExecStopPost)
### in /lib/systemd/system/anbox-container-manager.service

### Restart Anbox (have to do this after every reboot)
systemctl restart anbox-container-manager

There's no "back" button for now : run Anbox from app screen again to go back to Anbox app launcher.
